name: Base Styles
description: Base styles for the Fluent theme
type: core

form:
  fields:

    background:
      type: input.colorpicker
      label: Base Background
      default: "#6c9ec6"
    background-image:
      type: input.imagepicker
      label: Background Image
      default: "gantry-media://backgrounds/main/img-01.jpg"
    text-color:
      type: input.colorpicker
      label: Base Text Color
      default: "#1f2126"
    text-active-color:
      type: input.colorpicker
      label: Base Text Active Color
      default: "#745f9d"
