version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1513861050
layout:
  /top/:
    -
      - system-messages-9828
  /container-top/:
    -
      -
        '/navigation/ 90':
          -
            - 'logo-5992 10'
            - 'menu-2350 60'
            - 'search-8428 30'
        /slideshow/:
          -
            - custom-2985
      -
        'sidebar-top 10':
          -
            - social-1063
  /header/: {  }
  /above/: {  }
  /showcase/: {  }
  /utility/: {  }
  /feature/: {  }
  /container-main/:
    -
      -
        'sidebar 26': {  }
      -
        'mainbar 49':
          -
            - system-content-1120
      -
        'aside 25':
          -
            - position-position-8807
  /expanded/: {  }
  /extension/: {  }
  /bottom/: {  }
  /footer/: {  }
  /copyright/:
    -
      - branding-4688
  offcanvas:
    -
      - mobile-menu-7951
structure:
  top:
    type: section
    attributes:
      boxed: ''
      class: 'g-default-top section-horizontal-paddings'
  navigation:
    type: section
    attributes:
      boxed: '3'
      class: g-fluid-navigation
    block:
      variations: equal-height
  slideshow:
    type: section
    attributes:
      boxed: '3'
      class: 'g-default-slideshow section-horizontal-paddings'
  sidebar-top:
    type: section
    attributes:
      class: blurred
  container-top:
    attributes:
      boxed: ''
      class: ''
      extra: {  }
  header:
    attributes:
      boxed: ''
      class: 'g-default-header section-horizontal-paddings section-vertical-paddings-small'
  above:
    type: section
    attributes:
      boxed: ''
      class: g-default-above
  showcase:
    type: section
    attributes:
      boxed: ''
      class: 'g-default-showcase section-horizontal-paddings section-vertical-paddings'
  utility:
    type: section
    attributes:
      boxed: ''
      class: 'g-default-utility section-horizontal-paddings section-vertical-paddings'
  feature:
    type: section
    attributes:
      boxed: ''
      class: 'g-default-feature section-horizontal-paddings section-vertical-paddings'
  sidebar:
    type: section
    subtype: aside
    attributes:
      class: ''
  mainbar:
    type: section
    subtype: main
    title: Main
    attributes:
      class: ''
  aside:
    attributes:
      class: ''
  container-main:
    attributes:
      boxed: ''
      class: g-default-main
      extra: {  }
  expanded:
    type: section
    attributes:
      boxed: ''
      class: g-default-expanded
  extension:
    type: section
    attributes:
      boxed: ''
      class: g-default-extension
  bottom:
    type: section
    attributes:
      boxed: ''
      class: 'g-default-bottom section-horizontal-paddings section-vertical-paddings'
  footer:
    attributes:
      boxed: ''
      class: 'section-horizontal-paddings section-vertical-paddings'
  copyright:
    type: section
    attributes:
      boxed: ''
      class: section-horizontal-paddings
  offcanvas:
    attributes:
      swipe: '0'
content:
  logo-5992:
    block:
      class: 'nopaddingtop nopaddingbottom nomarginleft'
  menu-2350:
    block:
      class: 'nopaddingtop nopaddingbottom'
      variations: align-left
  search-8428:
    attributes:
      title: ''
      placeholder: ''
    block:
      class: 'fp-search hidden-phone hidden-tablet'
  custom-2985:
    title: Placeholder
    attributes:
      html: "<!-- You can safely remove this code -->\n<div class=\"hidden\">&nbsp;</div>"
    block:
      class: flush
  social-1063:
    attributes:
      items:
        -
          icon: 'fa fa-facebook fa-fw'
          text: ''
          link: 'https://www.facebook.com/RocketTheme'
          name: Facebook
        -
          icon: 'fa fa-twitter fa-fw'
          text: ''
          link: 'http://www.twitter.com/rockettheme'
          name: Twitter
        -
          icon: 'fa fa-vimeo'
          text: ''
          link: 'http://www.vimeo.com/'
          name: Vimeo
        -
          icon: 'fa fa-instagram'
          text: ''
          link: 'http://www.instagram.com/'
          name: Instagram
        -
          icon: 'fa fa-pinterest'
          text: ''
          link: 'http://www.pinterest.com'
          name: Pinterest
    block:
      variations: center
  position-position-8807:
    title: Aside
    attributes:
      key: aside
  branding-4688:
    block:
      variations: center
